name: GitHub Actions Demo

on:
  push:
    branches:
      - test

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
#    container: shadowsocks/android-ndk-go
    env:
      JVM_OPTS: -Xmx3500m
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          key: jars-{{ checksum "build.gradle" }}
          path: |
            ~/.gradle
            ~/.android/build-cache
      - run: ./gradlew assembleDebug check
        name: Run Build and Tests
      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: app/build/reports

